# Generated by Django 3.1.7 on 2021-02-23 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csp', models.CharField(max_length=40)),
                ('level', models.CharField(max_length=20)),
                ('certname', models.CharField(max_length=50)),
                ('certid', models.CharField(max_length=20)),
                ('certified_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('pdf_url', models.URLField()),
                ('validity', models.IntegerField(blank=True, null=True)),
                ('visibility', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
